# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - name: Deploy to Staging server
      uses: easingthemes/ssh-deploy@v2.0.7
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
        ARGS: "-rltgoDzvO"
        SOURCE: "puppet/"
        REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
        REMOTE_USER: ${{ secrets.REMOTE_USER }}
        TARGET: ${{ secrets.REMOTE_TARGET }}
    
    - name: Kick puppet
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: sudo puppet apply ${{ secrets.REMOTE_TARGET }}/manifests/init.pp
        # command: exit 1
        host: ${{ secrets.REMOTE_HOS }}
        username: ${{ secrets.REMOTE_USER }}
        privateKey: ${{ secrets.SERVER_SSH_KEY }}
    
    - name: send custom message
      uses: appleboy/telegram-action@master
      if: ${{ failure() }}
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          The action for ${{ github.event_name }} event failed.
  
  notify:
    runs-on: ubuntu-latest

    if: always()
    needs: build
    steps:
    - name: send alert message
      uses: appleboy/telegram-action@master
      if: env.WORKFLOW_CONCLUSION == 'failure'
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          2: The ${{ github.event_name }} event failed.

  


  
